grafana:
 ingress:
   enabled: true
   ingressClassName: traefik-ingress
   hosts:
    - grafana.datainfrapilot.com
   annotations:
     traefik.ingress.kubernetes.io/router.entrypoints: 'web'
     traefik.ingress.kubernetes.io/router.priority: '10'
